### ISSUE TITLE
Iterate on and design Posts

### ISSUE THREAD

**Issue by michaelschofield** [fontana-regional-library/frl#34]

**Comment by amy-actually** [comment]
Gave it a shot: 
[Rough Sketch](https://photos.google.com/share/AF1QipMRdNHjXx7DLqFAFusEtM41s1h0Ia_gQZBajZN8Y0logYw1tz7n_R1p-8P6tHxdkw/photo/AF1QipMSu-htQ6_uynoPUa2gGEcapnDBtTl9_d3hY0YE?key=eDVzMktVdTFqQndpYkJsSF8xa1FBWTI1SXBQZzJn)
album: https://photos.app.goo.gl/LQxJ2n1H3o2Uqkkh1
